tag/registry/registry.go

From
https://stackoverflow.com/questions/37758258/is-that-possible-to-get-image-id-from-docker-registry-v2#

Adjust headers to get correct digests

---

.gitignore
.travis.yml
Makefile
main.go
main_test.go
tag/local/local.go
tag/registry/registry.go
tag/tag.go
tag/tag_test.go

Sort by image creation datetime rather than by tag name.
Also separated naming and sort abstractions, which is good indeed.
Addressing this: https://github.com/ivanilves/lstags/issues/27 :tada:

Sort by DateTime

---

auth/auth.go
auth/basic/basic.go
auth/none/none.go
main.go
tag/registry/registry.go

https://github.com/ivanilves/lstags/issues/56

Support insecure Docker registries

---

README.md
main.go
main_test.go
tag/remote/remote.go
tag/tag.go
tag/tag_test.go

Brand new "registry<=>registry" image comparison algorithm
for Docker push instead of handicapped "docker<=>registry". :rocket: 
* Due to new algorithm, options `--pull` and `--push` are conflicting now! :warning: 
* Update tags with changed digests or not? Option `push-update` will help :wink:

Push in a more intelligent manner

---

docker/config/config.go
docker/config/config_test.go
fixtures/docker/config.json.corrupt

Trying to fix: https://github.com/ivanilves/lstags/issues/87

Added handling for possibly corrupt configs

---

Dockerfile
Makefile
README.md
scripts/prepare-docker-build.sh

Hey @ivanilves,
awesome project 💯 . I added a Dockerfile so that you can use your tool directly with docker. In future it would be great to have an tcp option for the docker engine. This would enable multistage builds and not the current workaround.

Add direct support for docker

---

main.go
tag/remote/remote.go

_Sometimes HTTP requests to Docker registry fail (the more tags we query the more :boom: :scream_cat:).
However we could retry on errors, if that has at least some sense (not for the 4XX of course)!_
Solving this old and nasty https://github.com/ivanilves/lstags/issues/29
Please see also: https://github.com/ivanilves/lstags/issues/85#issuecomment-342890182

Retry failed registry HTTP requests

---

Makefile
README.md
main.go
tag/tag.go
tag/tag_test.go
util/util.go
util/util_test.go

Some registries (`quay.io` reported) do not expose information about all tags for some repositories (`calico/cni` reported). So if we want to synchronize with them, but they "hide" interesting tags, we need to "assume" they have some tags they do not expose and just blindly get em! :roll_eyes: 
We assume tags `v1.6.1` and `v1.7.0` exist like this: `lstags quay.io/calico/cni=v1.6.1,v1.7.0`

Assume [some] tag names are present

---

README.md
api/v1/v1.go
api/v1/v1_test.go
main.go

Well, the next `v1.0.X` release should be a **stable** one! :muscle:
And the last thing we were missing is the fresh `README.md`

Prepare a first v1.0.X stable release

---

README.md

Looks like we forgot to add documentation on `--push-prefix` behavior :innocent:

NORELEASE: Document `--push-prefix` feature behavior

---

.gitignore
api/registry/registry.go
api/registry/registry_test.go
api/v1/v1.go
docker/client/client.go

Following issue https://github.com/ivanilves/lstags/issues/144

"Unhandicap" Pull and Push routines [ISSUE-144]

---

api/v1/v1.go
main.go
util/wait/wait.go

As stated in https://github.com/ivanilves/lstags/issues/146 we need to "try harder" while pulling or pushing Docker images.
This adds `wait.WithTolerance(done)` routine for pulls and pushes, so we will have errors logged and exit code set to non-zero, if something happens, but still most of the job will get done with "best effort" principle.

IMPROVE: Tolerate errors on `Pull` and `Push` actions

---

api/v1/v1.go
tag/remote/remote.go

Humbly trying to fix issues:
* https://github.com/ivanilves/lstags/issues/153 - do not use response if it is `nil` (we haven't stumbled upon this before because of pure luck)
* https://github.com/ivanilves/lstags/issues/154 - use `chan` instead of `map` while doing concurrent writes, as `chan` is kinda concurrency-safe

Fix nils and concurrent map writes

---

Makefile

this syntax works both on MacOSX and Linux, the one before was working only on Linux...

chore(CI): MacOSX-friendly scripts

---

api/v1/registry/container/container.go
api/v1/registry/container/container_test.go
api/v1/v1.go
api/v1/v1_test.go
main.go
tag/remote/remote.go

I try to avoid non-single scope PR but ...
* `-w, --wait-between` CLI opt to wait between batches of requests (extra layer of self-DoS protection)
* fix another "concurrent map writes" issue (not funny anymore, raising importance of https://github.com/ivanilves/lstags/issues/143) https://github.com/ivanilves/lstags/issues/154
* move registry package from `internal` to `v1` namespace (a stupid chore to make me happy)

Add delay between batches & one more "concurrent map write" fix

---

api/v1/registry/container/container_test.go

We forgot to cleanup Docker container in `TestRun`...

test(api/v1/registry/container): Fix `TestRun` cleanup

---

Gopkg.lock
api/v1/registry/client/client.go
api/v1/registry/container/container.go

https://github.com/ivanilves/lstags/issues/174
GCR is awesome as it implements best Docker registry API possible.
However, they removed `v1` API compatibility data from their API replies, and `lstags` :boom: on it.
The idea is to fix it now and later update `lstags` client so it could use advanced GCR features.

Fix basic GCR communication issues

---

api/v1/registry/client/client.go
api/v1/v1.go
main.go
repository/repository.go

Hey,
I encountered the problem that my registry does not support arbitrary paths for images.
To counter this I added support to exchange "/" with any customizable seperator via cli.
I also had an issue with the login on my quay enterprise registry, hence why I needed to change api/v1/registry/client/client.go:114 to use repository instead of registry. 
Kind regards

Add support to change PathSeperator

---

Makefile
api/v1/v1_test.go

In https://github.com/ivanilves/lstags/pull/179 we added path separator support 💪, but we forgot to explain it to our testing suite. Fixing it!

Set path separator in tests

---

api/v1/v1_test.go
repository/repository.go

Remove "filter" part from ref spec before parsing it - to not confuse parser. Fixes https://github.com/ivanilves/lstags/issues/199

fix: remove "filter" part from ref spec

---

api/v1/registry/client/auth/basic/store/store.go
api/v1/registry/client/auth/basic/store/store_test.go
api/v1/registry/client/auth/token.go
go.mod
go.sum
main.go

Need to support setting BASIC credentials for Artifactory to try to avoid things like https://github.com/ivanilves/lstags/issues/214 :man_shrugging:

feat(auth): Set BASIC auth with no respect to remote server

---

.circleci/config.yml
Makefile
api/v1/registry/client/request/request.go

Close #225 
I'm pretty certain this is all that's required to fix the pagination problems I was seeing with quay.io. I've also changed the tests to use bash instead of sh, as pushd and popd are only available in bash...at least on my Ubuntu 20.04 machine.

Fix pagination bug #225 and fix tests on Ubuntu

---

.circleci/config.yml
docker/config/config.go
docker/config/config_test.go

I could not get the latest version to push to my Amazon ECR registry and it seems to be because of this hardcoded `_json_key` username. I believe this is probably a separate issue to #214 because the breaking change was only introduced in v1.2.16.
I have also had to tweak the "Build release assets and binaries" Circle CI step to allow the build to succeed.
Thanks!

Fix incorrectly hardcoded Docker Authentication username

---

api/v1/registry/client/client.go
repository/repository.go
repository/repository_test.go
tag/remote/remote.go

closes https://github.com/ivanilves/lstags/issues/222

fix: Do NOT require list permissions on a single set of tags

---

repository/repository.go
repository/repository_test.go

closes https://github.com/ivanilves/lstags/issues/224
:information_source: `docker.io` is a fake fancy name for `registry.hub.docker.com`

fix(repository): ensure we parse docker.io repos correctly

---

.circleci/config.yml
api/v1/registry/client/client.go

Fixing https://github.com/ivanilves/lstags/issues/231 as `cli.Token` may be `nil`, but also, since it's an interface it can be a non-nil structure with a `nil` value :trollface:

fix(issue-231): "nil *Token pointer" panic
