tag/registry/registry.go

... to make it faster.
`32` is just a good starting point we should make it configureable...
https://github.com/ivanilves/lstags/issues/2

Concurrency for HTTP client/registry requests

---

tag/local/local.go

https://github.com/ivanilves/lstags/issues/3

Detect Docker API version

---

auth/auth.go
auth/basic/basic.go
auth/bearer/bearer.go
main.go
tag/registry/registry.go

:white_check_mark:  https://github.com/ivanilves/lstags/issues/7

Allow Bearer + HTTP basic

---

main.go

https://github.com/ivanilves/lstags/issues/18

Better exit messages

---

.travis.yml
README.md

https://github.com/ivanilves/lstags/issues/13

Add basic Travis steps

---

README.md

Because speaking normal words is now welcome in this world anymore...

Cooler README heading

---

.travis.yml
Makefile

Covering https://github.com/ivanilves/lstags/issues/23

Add Makefile support

---

.travis.yml
Makefile
main.go
main_test.go

Addressing https://github.com/ivanilves/lstags/issues/26

Add Integration testing of DockerHub

---

.travis.yml
Makefile
main.go
main_test.go
tag/local/local.go
tag/registry/registry.go
tag/tag.go
tag/tag_test.go

This PR is an "enabler" for:
* https://github.com/ivanilves/lstags/issues/24
* https://github.com/ivanilves/lstags/issues/27
* https://github.com/ivanilves/lstags/issues/28

Tag data structure

---

main.go
tag/local/local.go
tag/registry/registry.go
tag/tag.go

Addressing https://github.com/ivanilves/lstags/issues/28

Add Created time

---

main.go
tag/registry/registry.go
tag/tag.go

Addressing:
* https://github.com/ivanilves/lstags/issues/40
* https://github.com/ivanilves/lstags/issues/39

Refactor macht frei

---

.gitignore
.travis.yml
Makefile
main.go
main_test.go
scripts/github-create-release.sh
scripts/github-upload-assets.sh
version.go

So we will not waste our time on creating manual releases :triumph:

Add automatic release support (first iteration)

---

.travis.yml
Makefile
scripts/github-create-release.sh
scripts/github-upload-assets.sh

Release system improvement: Create releases only on PR merges

---

Makefile
README.md

README.md: Add information about binary releases

---

.travis.yml
Makefile
scripts/github-upload-assets.sh

Decouple release and deploy

---

docker/jsonconfig/jsonconfig.go
docker/jsonconfig/jsonconfig_test.go
fixtures/docker/config.json
fixtures/docker/config.json.invalid
fixtures/docker/config.json.irrelevant
main.go
main_test.go
tag/local/local.go
tag/registry/registry.go
tag/tag.go

Add transparent Docker registry authentication

---

main.go
main_test.go

Extract Docker registry from image name

---

README.md
main.go
main_test.go

* Solves: https://github.com/ivanilves/lstags/issues/51
* Unblocks: https://github.com/ivanilves/lstags/issues/53

Filter images by tag with regular expressions

---

main.go
tag/local/local.go
tag/tag.go

Pull Docker images matching filters specified

---

README.md
main.go
tag/local/local.go
tag/registry/registry.go

Renamed `--pull-images` to `--pull` + more concurrency

---

main.go

Fix fuzzy CLI help

---

Gopkg.lock
Gopkg.toml
main.go
tag/local/local.go

Fix authenticated pull requests

---

.gitignore
Makefile
README.md

*Once and for all! Solve https://github.com/ivanilves/lstags/issues/63*
First major refactor of `lstags`, which will open a road to further development.
This would be a long "work in progress" PR culminating in a pretty big release. :elephant: 
The emphasis here is placed on cleaner, safer code and importance of testing.

First refactor of L/S tags

---

README.md
app/app.go
main.go
tag/local/local.go

Re-Push images to specified registry

---

app/app.go
app/app_test.go
main.go

Refactor GeneratePathFromHostname

---

app/app.go
app/app_test.go
docker/client/api/version/version.go
docker/client/api/version/version_test.go
docker/client/client.go
docker/docker.go
docker/docker_test.go
main.go
tag/local/local.go
tag/local/local_test.go

Debloat local

---

auth/none/none.go
tag/remote/remote.go

Fix some quirks while operating gcr.io

---

.travis.yml
Makefile
auth/auth.go
docker/client/client.go
docker/docker.go
docker/docker_test.go
main.go
tag/remote/remote.go

[Re]Implement insecure registry handling

---

Dockerfile
Makefile
README.md
scripts/prepare-docker-build.sh

Refit Docker build to match our current demands

---

.travis.yml
Makefile

As long as we add more internal, not user-facing things, we need a way to stop spamming our releases :wink:

Added "NORELEASE" CI feature

---

Gopkg.lock
README.md
docker/client/client.go
main_test.go

Added naive "end2end" https://github.com/ivanilves/lstags/issues/85 job :triumph:

End2End integration testing!

---

.travis.yml
Makefile
README.md
scripts/wrapper.sh

We release new versions of `lstags` few times a week.
And every time I need to download it manually. Really?

Add invocation/update wrapper

---

docker/client/client.go
main.go

Solving https://github.com/ivanilves/lstags/issues/84 :wink:

Implement "Docker pull" retry

---

.travis.yml
Dockerfile
Makefile
ci_docker_daemon.json
main_test.go

Addressing https://github.com/ivanilves/lstags/issues/102

Extend CI with Docker TCP support

---

.gitignore
.travis.yml
Dockerfile
Gopkg.lock
Makefile
main_test.go
scripts/async-run.sh
scripts/async-wait.sh

Solving https://github.com/ivanilves/lstags/issues/104 :rocket: 
This lowers build time from 5-7min to 3-4min, so I am pretty happy.
_Caching Golang dependencies did not help to improve speed of builds (I measured 2nd and so on, 1st was slow of course). So reverted. We may go back to the topic again in future. For now it's resource waste IMO._

[try to]Speed-up Travis build

---

Makefile

Build Windows binary also! Maybe it is useless, but who knows? Let's be Windows-tolerant! :wink: :rainbow_flag:

Windows support

---

.travis.yml
Dockerfile
Makefile

Release Docker container on PR merge

---

api/api.go
docker/client/client.go
main.go

A naive and humble PoC to start solving https://github.com/ivanilves/lstags/issues/106

Refactor: API PoC

---

Makefile

Cleanup: remove some mess from application

---

.travis.yml
Dockerfile
README.md
api/v1/registry/registry.go
api/v1/registry/registry_test.go
tag/remote/remote.go
wait/wait.go

Prepare for review on https://goreportcard.com

---

.travis.yml
Makefile
README.md

Add coverage report

---

api/v1/v1_test.go

Our end2end integration test was missing pull and push actions, so we were missing:
* API testing completeness.
* our precious coverage points! :rage:

More coverage for the God of coverage

---

Makefile

NORELEASE/NOMERGE: Debug release system

---

api/v1/v1.go

Coverage of v1.go to the possible maximum!

---

tag/tag_test.go

Increase coverage, come hell or high water!

---

main.go

Solving https://github.com/ivanilves/lstags/issues/133

FEATURE: Daemon mode [ISSUE-133]

---

Gopkg.lock
Makefile
README.md
api/v1/v1_test.go
config/config.go
config/config_test.go
docker/config/config.go
docker/config/config_test.go
fixtures/config/config.yaml
fixtures/config/config.yaml.invalid
fixtures/config/config.yaml.irrelevant
fixtures/config/config.yaml.shared
fixtures/docker/config.json.badauth
main.go
util/fix/fix.go

ISSUE: https://github.com/ivanilves/lstags/issues/89
We need to enter the magic world of hipsters and hype, but how could we do it without YAML support? :wink: 
Kubernetes chart for `lstags`

FEATURE: YAML configuration file support [ISSUE-89]

---

api/registry/registry.go
api/v1/v1.go
api/v1/v1_test.go
repository/repository.go
repository/repository_test.go

BUGFIX: `pushPrefix` generation [ISSUE-137]

---

README.md

NORELEASE: To fail or not to fail?

---

Makefile
README.md
api/registry/registry_test.go
api_usage.go.sample

Add sample development environment initialization

---

.gitignore
.travis.yml
Makefile
README.md
scripts/async-run.sh
scripts/async-wait.sh
scripts/github-create-release.sh
scripts/travis_range.sh

*I'm back from my long vacations!* :joy: 
We need to go for https://github.com/ivanilves/lstags/issues/149 but before let's spend some time improving our CI system:

CI improvements

---

.travis.yml

chore(CI): NORELEASE fix semantic build check

chore(CI): NORELEASE fix semantic build check

---

.travis.yml
docker/config/config.go

ISSUE-174 Fix _json_key GCR authentication

---

.travis.yml
api/v1/registry/client/client.go
api/v1/registry/client/request/request.go

fix(API): ISSUE-185 Support paging when receiving tags

---

README.md
api/v1/registry/client/client.go
main.go
tag/local/local.go
tag/manifest/manifest.go
tag/remote/remote.go
tag/tag.go

v1-2-7: Some refactoring, fixes and change of defaults

---

api/v1/registry/client/cache/cache.go
api/v1/registry/client/client.go
api/v1/registry/client/request/request.go
api/v1/v1.go
main.go

Trying to solve this: https://github.com/ivanilves/lstags/issues/204 🤷‍♂ 😅

feat(ISSUE-204): Reduce "error 429" impact

---

api/v1/registry/client/cache/cache.go
api/v1/v1.go
api/v1/v1_test.go
main.go

Trying to fix issues on 
* data validation https://github.com/ivanilves/lstags/issues/213
* locking/concurrency https://github.com/ivanilves/lstags/issues/215 which may lead to program "hanging". 😱

Bugfix release: 1.2.12

---

.circleci/config.yml
Makefile
vendor/modules.txt

https://github.com/ivanilves/lstags/issues/212

Fix "`--version` option returns `CURRENT`" issue

---

.circleci/config.yml
Makefile
scripts/github-upload-assets.sh

Addressing https://github.com/ivanilves/lstags/issues/234
... and doing some long expected chores :slightly_smiling_face:

Release v1.2.22 (issue-234 + general security)

---

api/v1/registry/client/request/request.go

fix(issue-240): Accept indexes in OCI format
